name: Send Daily GMAT Question

on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 7:00 AM every day
  workflow_dispatch:     # Allows manual triggering of the workflow

permissions:
  contents: write  # Grants write permission to the repository contents

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true  # Use the token provided by GitHub Actions
        fetch-depth: 0  # Fetch all history so we can push changes

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Configure SMTP Server
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
      run: |
        echo "SMTP_SERVER=${SMTP_SERVER}" >> $GITHUB_ENV
        echo "SMTP_PORT=${SMTP_PORT}" >> $GITHUB_ENV
        echo "EMAIL_ADDRESS=${EMAIL_ADDRESS}" >> $GITHUB_ENV
        echo "EMAIL_PASSWORD=${EMAIL_PASSWORD}" >> $GITHUB_ENV
        echo "RECIPIENT_EMAILS=${RECIPIENT_EMAILS}" >> $GITHUB_ENV

    - name: Run the Script
      run: python script.py

    - name: Commit sent_questions.txt
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add sent_questions.txt
        git commit -m "Update sent questions"
        git push
